# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- powershell: |
    Write-Host "Running on Windows VM"
    systeminfo | findstr /B /C:"OS Name"
  displayName: 'Verify Windows Agent'